import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Check, Clock3, History, Plus, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import { formatNetTimeDifference, formatOvertimeMinutes } from "@shared/overtime";
import { TIME_OFF_REASON_LABELS, type Worker } from "@shared/schema";
import { EmailNotificationDetails } from "@/components/time/email-notification-details";
type Entry = { id: string; entryType: "OVERTIME" | "AUTHORISED_TIME_OFF"; employeeId: string; employeeName: string; workDate: string; startTime: string; finishTime: string; overtimeMinutes: number; status: "pending" | "approved" | "rejected"; notes: string; clientName?: string; timeOffReason?: string | null; approvedByName?: string | null };
type Summary = { approvedOvertimeMinutes: number; approvedTimeOffMinutes: number; pendingOvertimeMinutes: number; pendingTimeOffMinutes: number; netMinutes: number };
const today = () => new Date().toISOString().slice(0, 10);
export default function TimeOvertime() {
  const { toast } = useToast(); const [employeeId, setEmployeeId] = useState("all"); const [status, setStatus] = useState("all"); const [type, setType] = useState("all"); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const { user } = useAuth();
  const isAdmin = ["admin", "superadmin"].includes(String(user?.role || "").toLowerCase());
  const [createOpen, setCreateOpen] = useState(false); const [timelineOpen, setTimelineOpen] = useState(false); const [auditEntry, setAuditEntry] = useState<Entry | null>(null); const [rejection, setRejection] = useState<Entry | null>(null);
  const [form, setForm] = useState({ employeeId: "", workDate: today(), startTime: "", finishTime: "", reason: "gap_between_jobs", otherReason: "", notes: "", overrideConflictReason: "" });
  const url = useMemo(() => { const p = new URLSearchParams(); if (employeeId !== "all") p.set("employeeId", employeeId); if (status !== "all") p.set("status", status); if (type !== "all") p.set("type", type); if (from) p.set("from", from); if (to) p.set("to", to); return `/api/time${p.toString() ? `?${p}` : ""}`; }, [employeeId, status, type, from, to]);
  const { data = { entries: [], summary: {} as Summary }, isLoading } = useQuery<{ entries: Entry[]; summary: Summary }>({ queryKey: [url] });
  const { data: workers = [] } = useQuery<Worker[]>({ queryKey: ["/api/workers"] });
  const { data: audit = [] } = useQuery<any[]>({ queryKey: ["/api/overtime", auditEntry?.id, "audit"], enabled: Boolean(auditEntry) });
  const timelineUrl = timelineOpen && employeeId !== "all" && from ? `/api/time/timeline?employeeId=${employeeId}&date=${from}` : "";
  const { data: timeline } = useQuery<{ items: any[] }>({ queryKey: [timelineUrl], enabled: Boolean(timelineUrl) });
  useEffect(() => {
    const requestedId = new URLSearchParams(window.location.search).get("entry");
    const requested = requestedId ? data.entries.find(entry => entry.id === requestedId) : undefined;
    if (requested) setAuditEntry(requested);
  }, [data.entries]);
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ["/api/time"] }); queryClient.invalidateQueries({ queryKey: ["/api/time/my"] }); };
  const action = useMutation({ mutationFn: async ({ entry, kind, reason }: { entry: Entry; kind: "approve" | "reject" | "reopen"; reason?: string }) => (await apiRequest("POST", `${entry.entryType === "AUTHORISED_TIME_OFF" ? "/api/time-off" : "/api/overtime"}/${entry.id}/${kind}`, reason ? { reason } : {})).json(), onSuccess: () => { refresh(); toast({ title: "Time entry updated" }); }, onError: (error: Error) => toast({ title: "Could not update entry", description: error.message, variant: "destructive" }) });
  const create = useMutation({ mutationFn: async () => (await apiRequest("POST", "/api/time-off", form)).json(), onSuccess: () => { refresh(); setCreateOpen(false); setForm({ employeeId: "", workDate: today(), startTime: "", finishTime: "", reason: "gap_between_jobs", otherReason: "", notes: "", overrideConflictReason: "" }); toast({ title: "Authorised Time Off created", description: "The approved entry and authorising manager are recorded." }); }, onError: (error: Error) => toast({ title: "Could not authorise Time Off", description: error.message, variant: "destructive" }) });
  const resend = useMutation({ mutationFn: async (entry: Entry) => (await apiRequest("POST", `/api/time-off/${entry.id}/resend-notification`)).json(), onSuccess: () => toast({ title: "Time Off notification sent successfully." }), onError: (error: Error) => toast({ title: "Could not resend Time Off notification", description: error.message, variant: "destructive" }) });
  const statusClass = (s: string) => s === "approved" ? "bg-emerald-100 text-emerald-800" : s === "rejected" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800";
  return <div className="mx-auto max-w-7xl space-y-6 pb-10"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="flex items-center gap-2 text-sm font-semibold text-red-700"><Clock3 className="h-5 w-5" />Management time review</p><h1 className="mt-1 text-2xl font-bold">Time &amp; Overtime</h1><p className="mt-1 text-sm text-slate-500">Approved overtime and authorised Time Off remain separate. Net time difference is management information only.</p></div><Button onClick={() => setCreateOpen(true)} className="bg-slate-900 hover:bg-slate-800"><Plus className="mr-2 h-4 w-4" />Authorise Time Off</Button></div>
    <section className="grid grid-cols-2 gap-4 lg:grid-cols-5">{[["Approved Overtime", data.summary.approvedOvertimeMinutes, "emerald"], ["Approved Time Off", data.summary.approvedTimeOffMinutes, "slate"], ["Net Difference", data.summary.netMinutes, "red"], ["Pending Overtime", data.summary.pendingOvertimeMinutes, "amber"], ["Pending Time Off", data.summary.pendingTimeOffMinutes, "amber"]].map(([label, value, colour]) => <div key={String(label)} className={`rounded-xl border p-4 ${colour === "emerald" ? "border-emerald-200 bg-emerald-50" : colour === "red" ? "border-red-200 bg-red-50" : colour === "amber" ? "border-amber-200 bg-amber-50" : "border-slate-200 bg-slate-50"}`}><p className="text-xs font-semibold uppercase text-slate-600">{label}</p><p className="mt-1 text-xl font-bold">{label === "Net Difference" ? formatNetTimeDifference(Number(value || 0)) : formatOvertimeMinutes(Number(value || 0))}</p></div>)}</section>
    <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger><SelectValue placeholder="Employee" /></SelectTrigger><SelectContent><SelectItem value="all">All employees</SelectItem>{workers.filter(w => w.isActive !== false).map(w => <SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</SelectContent></Select><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem><SelectItem value="OVERTIME">Overtime</SelectItem><SelectItem value="AUTHORISED_TIME_OFF">Authorised Time Off</SelectItem></SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="approved">Approved</SelectItem><SelectItem value="rejected">Rejected</SelectItem></SelectContent></Select><Input type="date" value={from} onChange={e => setFrom(e.target.value)} aria-label="From date" /><Input type="date" value={to} onChange={e => setTo(e.target.value)} aria-label="To date" /></div>{employeeId !== "all" && from && <Button variant="outline" size="sm" className="mt-3" onClick={() => setTimelineOpen(true)}>View daily timeline</Button>}</section>
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b p-4 sm:px-6"><h2 className="font-semibold">Time records</h2><p className="text-sm text-slate-500">{data.entries.length} records shown</p></div>{isLoading ? <p className="p-6 text-sm text-slate-500">Loading time records…</p> : data.entries.length ? <div className="divide-y">{data.entries.map(entry => <article key={entry.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:px-6"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{entry.employeeName}</p><Badge className={entry.entryType === "OVERTIME" ? "bg-red-100 text-red-800" : "bg-slate-200 text-slate-800"}>{entry.entryType === "OVERTIME" ? "Overtime" : "Authorised Time Off"}</Badge><Badge className={statusClass(entry.status)}>{entry.status}</Badge></div><p className="mt-1 text-sm text-slate-600">{entry.workDate} · {entry.startTime}–{entry.finishTime}{entry.clientName ? ` · ${entry.clientName}` : ""}</p>{entry.notes && <p className="mt-1 text-xs text-slate-500">{entry.notes}</p>}{entry.status === "approved" && entry.approvedByName && <p className="mt-1 text-xs text-emerald-700">Approved by {entry.approvedByName}</p>}</div><div className="flex flex-wrap items-center gap-2"><span className="mr-2 text-lg font-bold">{formatOvertimeMinutes(entry.overtimeMinutes)}</span>{entry.status === "pending" && <><Button size="sm" onClick={() => action.mutate({ entry, kind: "approve" })} disabled={action.isPending}><Check className="mr-1 h-3.5 w-3.5" />Approve</Button><Button size="sm" variant="outline" className="text-red-700" onClick={() => setRejection(entry)}><X className="mr-1 h-3.5 w-3.5" />Reject</Button></>}{entry.status !== "pending" && <Button size="sm" variant="outline" onClick={() => action.mutate({ entry, kind: "reopen" })}><RotateCcw className="mr-1 h-3.5 w-3.5" />Reopen</Button>}{isAdmin && entry.entryType === "AUTHORISED_TIME_OFF" && <Button size="sm" variant="outline" disabled={resend.isPending} onClick={() => resend.mutate(entry)}>Resend notification</Button>}<Button size="sm" variant="ghost" onClick={() => setAuditEntry(entry)}><History className="mr-1 h-3.5 w-3.5" />History</Button></div></article>)}</div> : <p className="p-8 text-center text-sm text-slate-500">No records match these filters.</p>}</section>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Authorise Time Off</DialogTitle></DialogHeader><div className="space-y-3"><Select value={form.employeeId} onValueChange={employeeId => setForm(f => ({ ...f, employeeId }))}><SelectTrigger><SelectValue placeholder="Employee" /></SelectTrigger><SelectContent>{workers.map(w => <SelectItem key={w.id} value={w.id}>{w.name}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-3 gap-2"><Input type="date" value={form.workDate} onChange={e => setForm(f => ({ ...f, workDate: e.target.value }))} /><Input type="time" value={form.startTime} onChange={e => setForm(f => ({ ...f, startTime: e.target.value }))} /><Input type="time" value={form.finishTime} onChange={e => setForm(f => ({ ...f, finishTime: e.target.value }))} /></div><Select value={form.reason} onValueChange={reason => setForm(f => ({ ...f, reason }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(TIME_OFF_REASON_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>{form.reason === "other" && <Input placeholder="Other reason" value={form.otherReason} onChange={e => setForm(f => ({ ...f, otherReason: e.target.value }))} />}<Textarea placeholder="Notes (optional)" value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))} /><Textarea placeholder="Override reason (only if a scheduled job conflicts)" value={form.overrideConflictReason} onChange={e => setForm(f => ({ ...f, overrideConflictReason: e.target.value }))} /><Button className="w-full bg-slate-900" disabled={!form.employeeId || !form.startTime || !form.finishTime || create.isPending} onClick={() => create.mutate()}>{create.isPending ? "Authorising…" : "Authorise"}</Button></div></DialogContent></Dialog>
    <Dialog open={Boolean(rejection)} onOpenChange={open => !open && setRejection(null)}><DialogContent><DialogHeader><DialogTitle>Reject time entry</DialogTitle></DialogHeader><Textarea id="reject-time-reason" placeholder="Reason (optional)" /><Button className="bg-red-600" onClick={() => { const reason = (document.getElementById("reject-time-reason") as HTMLTextAreaElement)?.value; if (rejection) action.mutate({ entry: rejection, kind: "reject", reason }); setRejection(null); }}>Reject</Button></DialogContent></Dialog>
     <Dialog open={Boolean(auditEntry)} onOpenChange={open => !open && setAuditEntry(null)}><DialogContent><DialogHeader><DialogTitle>Audit history</DialogTitle></DialogHeader><ol className="space-y-3">{audit.filter(event => !event.action.startsWith("TIME_")).map(event => <li key={event.id} className="border-l-2 pl-3"><p className="capitalize font-medium">{event.action.replaceAll("_", " ").toLowerCase()}</p><p className="text-xs text-slate-500">{event.actorName} · {new Date(event.createdAt).toLocaleString("en-ZA")}</p>{event.details && <p className="mt-1 text-xs text-slate-500">{event.details}</p>}</li>)}</ol><EmailNotificationDetails audit={audit} /></DialogContent></Dialog>
    <Dialog open={timelineOpen} onOpenChange={setTimelineOpen}><DialogContent><DialogHeader><DialogTitle>Daily timeline</DialogTitle></DialogHeader><div className="space-y-3">{timeline?.items?.map((item: any) => <div key={`${item.type}-${item.id}`} className={`rounded-lg border p-3 ${item.type === "TIME_OFF" ? "border-slate-300 bg-slate-50" : item.type === "OVERTIME" ? "border-red-200 bg-red-50" : "border-blue-200 bg-blue-50"}`}><p className="text-xs font-bold">{item.type === "JOB" ? "NORMAL WORK / JOB" : item.type === "TIME_OFF" ? "TIME OFF" : "OVERTIME"}</p><p className="font-semibold">{item.startTime}–{item.finishTime} · {item.label}</p></div>) || <p className="text-sm text-slate-500">No timeline items.</p>}</div></DialogContent></Dialog>
  </div>;
}