import { useQuery } from "@tanstack/react-query";
import { useParams } from "wouter";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";

type Report = any;

export default function TreatmentReportPrint() {
  const { id } = useParams<{ id: string }>();
  const { data: report, isLoading, error } = useQuery<Report>({ queryKey: [`/api/treatment-reports/${id}`] });
  if (isLoading) return <div className="p-12 text-center text-slate-500">Loading formal treatment report…</div>;
  if (error || !report) return <div className="p-12 text-center text-red-700">This treatment report could not be loaded.</div>;
  const precautions = "Keep children and pets out of treated areas. Ventilate the area well. Cover food and food preparation surfaces. Do not clean treated surfaces for five days and do not tamper with bait. Increased pest activity shortly after treatment can be normal; allow approximately seven days for treatment to take effect.";
  return <main className="min-h-screen bg-slate-100 py-8 print:bg-white print:py-0"><div className="mx-auto mb-4 flex max-w-4xl justify-end print:hidden"><Button onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Print / save as PDF</Button></div><article className="mx-auto max-w-4xl bg-white p-8 shadow-sm print:max-w-none print:shadow-none"><header className="border-b-4 border-emerald-700 pb-5"><div className="flex justify-between gap-6"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Terminators JobFlow</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Pest Control Treatment Report</h1><p className="mt-2 text-sm text-slate-600">Report {report.reportNumber || "—"} · {report.reportDate}</p></div><div className="text-right text-sm text-slate-600"><p className="font-bold text-slate-900">{report.tradingName || "Client"}</p><p className="max-w-xs">{report.siteAddress || "Site address not recorded"}</p></div></div></header>
    <Section title="Service Details"><Grid rows={[["Job number", report.jobNumber], ["Contract number", report.contractNumber || "Once-off"], ["Service type", report.serviceType], ["Treatment type", display(report.treatmentType)], ["Technician", report.technicianName], ["PCO registration", report.pcoRegistrationNumber || "—"], ["Start time", time(report.startTime)], ["Finish time", time(report.finishTime)], ["Time on site", report.timeOnSiteMinutes != null ? `${report.timeOnSiteMinutes} minutes` : "—"]]} /></Section>
    <Section title="Pests and Areas"><Grid rows={[["Areas treated", (report.areas || []).map((area: any) => area.otherDescription || display(area.area)).join(", ")], ["Pests identified", (report.pests || []).map((pest: any) => `${display(pest.pestType)} (${display(pest.infestationLevel)})`).join(", ")], ["Premises cleanliness", display(report.cleanlinessAssessment)], ["Cleanliness comments", report.cleanlinessComments || "—"]]} /></Section>
    <Section title="Equipment Serviced">{(report.equipment || []).length ? <table className="w-full border-collapse text-sm"><thead><tr className="bg-slate-100 text-left"><th className="p-2">Equipment</th><th className="p-2">Quantity</th><th className="p-2">Product / notes</th></tr></thead><tbody>{report.equipment.map((item: any) => <tr key={item.id} className="border-b"><td className="p-2">{item.equipmentType}</td><td className="p-2">{item.quantity}</td><td className="p-2">{[item.productType, item.notes].filter(Boolean).join(" · ") || "—"}</td></tr>)}</tbody></table> : <p className="text-sm">No equipment serviced.</p>}</Section>
    <Section title="Products Used">{report.noProductUsed ? <p className="text-sm">No pesticide/product was used during this visit.</p> : <table className="w-full border-collapse text-sm"><thead><tr className="bg-slate-100 text-left"><th className="p-2">Product</th><th className="p-2">Formulation</th><th className="p-2">Registration</th><th className="p-2">Quantity</th><th className="p-2">Mixture / dilution</th></tr></thead><tbody>{(report.products || []).map((item: any) => <tr key={item.id} className="border-b"><td className="p-2">{item.productName}</td><td className="p-2">{item.formulation || "—"}</td><td className="p-2">{item.registrationNumber || "—"}</td><td className="p-2">{item.quantityUsed} {item.unit}</td><td className="p-2">{item.mixtureDilution || "—"}</td></tr>)}</tbody></table>}</Section>
    <Section title="Recommendations and Action Required"><p className="whitespace-pre-wrap text-sm">{report.treatmentNotes || report.recommendations || "No additional recommendations recorded."}</p>{report.actionRequired && <div className="mt-3 rounded border border-amber-400 bg-amber-50 p-3 text-sm text-amber-950"><strong>Action required:</strong> {report.actionReason}</div>}</Section>
    <Section title="Customer Precautions"><p className="text-sm leading-6">{precautions}</p></Section>
    <Section title="Client Confirmation"><Grid rows={[["Client representative", report.customerName || "—"], ["Signature", report.signatureUnavailable ? `Unavailable — ${report.signatureUnavailableReason || "reason not recorded"}` : report.customerSignature ? "Captured electronically" : "Not captured"]]} />{report.customerSignature && <img src={report.customerSignature} alt="Client signature" className="mt-3 h-20 border-b border-slate-400 object-contain" />}</Section>
    {(report.photos || []).length > 0 && <Section title="Site Evidence"><div className="grid grid-cols-3 gap-3">{report.photos.map((photo: any) => <img key={photo.id} src={photo.fileUrl} alt={photo.fileName || "Treatment evidence"} className="h-40 w-full rounded object-cover" />)}</div></Section>}
    <footer className="mt-10 border-t pt-4 text-xs text-slate-500">This report was digitally completed in Terminators JobFlow and is retained with its audit history.</footer>
  </article></main>;
}
function display(value: unknown) { return String(value || "—").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase()); }
function time(value: unknown) { return value ? new Date(String(value)).toLocaleString("en-ZA") : "—"; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7"><h2 className="mb-3 border-b border-slate-300 pb-1 text-base font-bold text-slate-900">{title}</h2>{children}</section>; }
function Grid({ rows }: { rows: Array<[string, unknown]> }) { return <dl className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">{rows.map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-0.5">{String(value || "—")}</dd></div>)}</dl>; }